name: Print environment variables
on: push
env:
  EXAMPLE: Defined by workflow level
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The variable EXAMPLE is: ${EXAMPLE}"
      - env:
          EXAMPLE: Defined by step level
        - run: echo "The variable EXAMPLE is: ${EXAMPLE}"
