name: Print environment variables
on: push
jobs:
  printing:
    runs-on: ubuntu-latest
    env:
      EXAMPLE: job-level
    steps:
      - name: First step
        run: echo "Hello, I am ${EXAMPLE}!"
      - name: Second step
        run: echo "Hello, I am ${EXAMPLE}!"
          env:
            EXAMPLE: step-level
      - uses: actions/checkout@v4
